export enum Patterns {
  USER_GET_WITH_ID = 'USER_GET_WITH_ID',
  CREATE_PROFILE = 'PROFILE_CREATE_PROFILE',
  GET_WITH_ID = 'PROFILE_GET_ID',
  GET_WITH_USER_ID = 'PROFILE_GET_WITH_USER_ID',
  UPDATE_PROFILE = 'PROFILE_UPDATE_PROFILE',
}
